ignore:
  - build
  - examples
  - libcaf_core/caf/decorator
  - libcaf_core/src/decorator
  - libcaf_core/test
  - libcaf_io/test
  - libcaf_net/test
  - libcaf_openssl
  - libcaf_test
  - tools
coverage:
  status:
    project:
      default:
        threshold: 1% # we have some fluctuation from nondeterminism alone
